#!/bin/bash

###----------------------------------------------------------
### VARIABLES ###

GREEN="$(tput setaf 2)"
RESET="$(tput sgr0)"
BLUE="$(tput setf 1)"
CYAN="$(tput setf 3)" 
RED="$(tput setf 4)" 
user=`whoami`
execdir=$HOME/PIS
base="base.txt"
aur="aur.txt"
gitrepos="gitrepos.txt"

###---------------------------------------------------------
### FUNCTIONS ###

### SEPERATOR  ##

sep() {
    echo -e "\n"
    for i in $( seq 1 $COLUMNS ); do echo -n "$1"; done
    echo -e "\n"
}

#[[## INSTALLING PACKAGES (PACMAN,AUR) ##]]#

install_packages_dir() {
    echo ""
    echo -ne "\r[ ] Installing packages using pacman ..." 
    sudo pacman -Syyu --noconfirm &>/dev/null
	while read line;
	do
		if [ "${line:0:1}" != "#" ] && [ "${#line}" != 0 ]; then
            sudo pacman -S "$line" --noconfirm &>/dev/null
		fi
	done < $execdir/$base
    echo -ne "\r[*] Installing packages using pacman [Done]" 
}


install_packages_aur() {
    echo ""
    echo -ne "\r[ ] Installing packages from AUR ..." 
	while read line;
	do
        if [ "${line:0:1}" != "#" ] && [ "${#line}" != 0 ]; then
            cd $HOME 
            git clone https://aur.archlinux.org/"$line".git &>/dev/null
            cd $HOME/$line 
            makepkg -si --noconfirm &>/dev/null
            rm $HOME/$line -rf 
        fi
	done < $execdir/$aur
    echo -ne "\r[*] Installing packages from AUR [Done]" 
}

#[[## DOWNLOADING GITREPOS AND SETTING DOTFILES ##]]#

gitrepos_download() {
    echo ""
    echo -ne "\r[ ] Downloading git Repos ..." 
	while read line;
	do
        if [ "${line:0:1}" != "#" ] && [ "${#line}" != 0 ]; then
            cd $HOME 
            repo=`echo $line | cut -d '|' -f1`
            git clone "$repo" &>/dev/null
        fi
	done < $execdir/$gitrepos
    echo -ne "\r[*] Downloading git Repos [Done]"
}

install_dotfiles() {
    echo ""
    echo -ne "\r[ ] Installing Dotfiles ..." 
    if [ -f $HOME/.bashrc ]; then rm $HOME/.bashrc; fi
    if [ -f $HOME/.bash_profile ]; then rm $HOME/.bash_profile; fi 
	ls -Al $HOME/.dotfiles | awk '{print $9}' | while read line;
	do
		if [ "$line" != .config ] && [ "$line" != .git ] && [ ${#line} != 0 ]; then ln -s $HOME/.dotfiles/"$line" $HOME/"$line"; fi
	done
	ls -Al $HOME/.dotfiles/.config | awk '{print $9}' | while read line;
	do
        if [ ${#line} != 0 ]; then ln -s $HOME/.dotfiles/.config/"$line" $HOME/.config/"$line"; fi
	done
    echo -ne "\r[*] Installing Dotfiles [Done]"
}

#[[## INIT ##]]#

logo() {
	echo -e "\n${CYAN}POST-INSTALLATON-SCRIPT\n-----------------------${RESET}\n"
}

is_root() {
	if [ "$user" == "root" ]; then
		echo -e "${RED}\nERROR : Do not RUN as ROOT!. stopping script.${RESET}"
		sep "="
		exit 1
	fi
}

start_qn() {
	echo "Hey $USER",
	read -p "Start installer ? (y/n) : " yes_no
	if [ "$yes_no" != y ] && [ "$yes_no" != Y ]; then
		echo -e "${RED}\nERROR : Your input caused the installer to stop.${RESET}"
		sep "="
		exit 1
	fi
}

req_filenfolders() {
	if [ ! -d "$HOME/.config" ]; then
		mkdir $HOME/.config
	fi
	if [ ! -f "$execdir/$base" ] || [ ! -f "$execdir/$gitrepos" ] || [ ! -f "$execdir/$aur" ];  then
		echo -e "${RED}\nERROR : Required file/files [base,aur,gitrepos] not found. Stopping script.${RESET}"
		sep "="
		exit 1
	else
		echo -e "${GREEN}\nRequired files [base,aur,gitrepos] satisfied.${RESET}"
	fi
}

init() {
	logo
	is_root
	start_qn
	req_filenfolders 
}

#[[## reboot ##]]#

rebooot() {
    echo -e "\n${GREEN}The Installation was succesfull.\nGoing for a reboot in 10 sec (CTRL-C to cancel).${RESET}\n"
    for i in $( seq 10 -1 0 ); do 
        echo -ne "\rThe system will reboot in $i seconds ..."
        sleep 1
    done
    sep "="
	sudo reboot
}

#[[## EXTRA SETUP ##]]#

setup_home() {
	cd $HOME
	mkdir Documents Pictures Files Music Videos Downloads
	mkdir $HOME/Pictures/Screenshots
	mv $HOME/Wallpapers $HOME/Pictures/
	mv $HOME/Suckless-builds/ $HOME/Files/
	mv $HOME/Books $HOME/Files/
	mv $HOME/PIS/ $HOME/Files/
}

warp_setup() {
	sudo systemctl enable warp-svc.service &> /dev/null
	sudo systemctl start warp-svc &> /dev/null
	warp-cli register &> /dev/null
	warp-cli connect &> /dev/null
	warp-cli set-families-mode full &> /dev/null
}

build_suckless(){
	ls -l $HOME/Files/Suckless-builds | awk '{print $9}' | while read line;
	do
		cd $HOME/Files/Suckless-builds/$line
		sudo make clean install &> /dev/null
        cd $HOME/Files/Suckless-builds
	done
}

extra_setup() {
    echo ""
    echo -ne "\r[ ] Additional Setup ..." 
	setup_home
	build_suckless
	warp_setup
    echo -ne "\r[*] Additional Setup [Done]" 
}

###----------------------------------------------------------
### MAIN-FUNCTION ###

main() {
	clear
	sep "="
	init 
	sep "-"
	install_packages_dir 
	sep "-"
	install_packages_aur
	sep "-"
	gitrepos_download
	sep "-"
	install_dotfiles
	sep "-"
	extra_setup
	sep "-"
	rebooot
}

###----------------------------------------------------------
### EXECUTION ###

main

###----------------------------------------------------------
### END ###
