#!/bin/bash

###----------------------------------------------------------
### VARIABLES ###

GREEN="$(tput setaf 2)"
RESET="$(tput sgr0)"
BLUE="$(tput setf 1)"
CYAN="$(tput setf 3)" 
RED="$(tput setf 4)" 
user=`whoami`
execdir=$HOME/PIS
base="base.txt"
aur="aur.txt"
gitrepos="gitrepos.txt"

### ARTWORK ###



###---------------------------------------------------------
### FUNCTIONS ###

### SEPERATOR  ##

sep() {
	echo -e "\n${CYAN}--------------------------------------------------------------------------------------------------------------------------------------------------------------${RESET}\n"

}

#[[## INSTALLING PACKAGES (PACMAN,AUR) ##]]#

install_packages_dir() {
	echo -e "${GREEN}\nDownloading and Installing packages (with pacman)\n-------------------------------------------------${RESET}\n"
	while read line;
	do
		if [ "${line:0:1}" == "#" ]; then
			if [ "${line:0:3}" == "###" ]; then
				echo -e "\n${GREEN}[Installing $line]${RESET}\n"
			fi
		else
			if [ "${#line}" != 0 ]; then
				sudo pacman -S "$line" --noconfirm
			fi
		fi

	done < $execdir/$base
}


install_packages_aur() {
	echo -e "${GREEN}Downloading and Installing packages (from aur)\n--------------------------------------------${RESET}"
	while read line;
	do
		if [ "${line:0:1}" == "#" ]; then
			if [ "${line:0:3}" == "###" ]; then
				echo -e "\n${GREEN}[Installing $line]${RESET}\n"
			fi
		else
			if [ "${#line}" != 0 ]; then
				cd ~/
				git clone https://aur.archlinux.org/"$line"
				cd ~/$line
				makepkg -si
				cd ~/
				sudo rm ~/$line -r

			fi
		fi

	done < $execdir/$aur
}

#[[## DOWNLOADING GITREPOS AND SETTING DOTFILES ##]]#

gitrepos_download() {
	echo -e "$\n{GREEN}Downloading Git repos\n----------------------${RESET}\n"
	cd ~/
	while read line;
	do
		if [ "${line:0:1}" == "#" ]; then
			if [ "${line:0:3}" == "###" ]; then
				echo -e "\n${GREEN}[Installing $line]${RESET}\n"
			fi
		else
			if [ "${#line}" != 0 ]; then
				cd ~/
				repo=`echo $line | cut -d '|' -f1`
				heading=`echo $line | cut -d '|' -f2`
				echo "\n${GREEN}Cloning $line ...${RESET}\n"
				git clone "$repo"
			fi
		fi
	done < $execdir/$gitrepos
}

install_dotfiles() {
	echo -e "\n${GREEN}Installing .dotfiles\n--------------------${RESET}\n"
	rm ~/.bashrc ~/.bash_profile
	cd ~/
	ls -Al ~/.dotfiles | awk '{print $9}' | while read line;
	do
		if [ "$line" != .config ] || [ "$line" != .git ]; then
			ln -s ~/.dotfiles/"$line" ~/"$line"
		fi
	done
	ls -Al ~/.dotfiles/.config | awk '{print $9}' | while read line;
	do
		ln -s ~/.dotfiles/"$line" ~/"$line"
	done
}

#[[## INIT ##]]#

logo() {
	echo -e "\n${CYAN}POST-INSTALLATON-SCRIPT\n-----------------------${RESET}\n"
}

is_root() {
	if [ "$user" == "root" ]; then
		echo -e "${RED}\nERROR : Do not RUN as ROOT!. stopping script.\n${RESET}"
		sep
		exit 1
	fi
}

start_qn() {
	echo "Hey $USER",
	read -p "Start installer ? (y/n) : " yes_no
	if [ "$yes_no" != y ] && [ "$yes_no" != Y ]; then
		echo -e "${RED}\nERROR : Your input caused the installer to stop.${RESET}\n"
		sep
		exit 1
	fi
}

req_filenfolders() {
	if [ ! -d "$HOME/.config" ]; then
		mkdir $HOME/.config
	fi
	if [ -f "$execdir/$base.txt" ] || [ -f "$execdir/$gitrepos.txt" ] || [ -f "$execdir/$aur.txt" ];  then
		echo -e "${RED}\nERROR : Required file/files [base,aur,gitrepos] not found. Stopping script.\n${RESET}"
		sep
		exit 1
	else
		echo -e "${GREEN}\nRequired files [base,aur,gitrepos] satisfied.\n${RESET}"
	fi
}

init() {
	logo
	is_root
	start_qn
	req_filenfolders 
}

#[[## reboot ##]]#

rebooot() {
	echo -e "\n${GREEN}The Installation was succesfull.\n Going for a reboot in 5 sec.${RESET}\n"
	sep
	sleep 5
	sudo reboot
}

#[[## EXTRA SETUP ##]]#

setup_home() {
	cd ~/
	mkdir Documents Pictures Files Music Videos Downloads
	mkdir ~/Pictures/Screenshots
	cd ~/
	mv ~/Wallpapers Pictures/
	mv ~/dm-scripts/ Files/
	mv ~/suckless-builds/ Files/
	mv ~/Books Files/
	mv ~/PIS/ Files/
}

warp_setup() {
	sudo systemctl enable warp-svc --now
	warp-cli register
	warp-cli connect
	warp-cli set-families-mode full

}

build_suckless(){
	cd ~/Files/Suckless
	ls -l | awk '${print $9}' | while read line;
	do
		cd $line
		sudo make clean install
		cd ..
	done
}

extra_setup() {
	echo -e "\n${BLUE}RUNNING ADDITIONAL SETUP\n ------------------------${RESET}\n"
	setup_home
	warp_setup
	build_suckless
}

###----------------------------------------------------------
### MAIN-FUNCTION ###

main() {
	clear
	sep
	init 
	sep
	install_packages_dir
	sep
	install_packages_aur
	sep
	gitrepos_download
	sep
	install_dotfiles
	sep
	extra_setup
	sep
	rebooot
}

###----------------------------------------------------------
### EXECUTION ###

main

###----------------------------------------------------------
### END ###
